version: "3.7"
volumes:
    postgres-data:
    redis-data:
networks:
    frontend:
    backend:
services:
    nginx-server:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - frontend
            - backend

    php-fpm:
        image: jkaninda/laravel-php-fpm
        working_dir: /var/www/app
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - backend

    postgres:
        image: postgres:latest
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: rl43s2of
            POSTGRES_USER: postgres
            POSTGRES_DB: autenticacion
            PGDATA: /var/lib/postgresql/data
        networks:
            - backend

    adminer:
        image: adminer
        restart: always
        ports:
        - 8081:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
            ADMINER_DESIGN: price
        networks:
        - backend

    redis:
        image: redis:latest
        sysctls:
            - net.core.somaxconn=511
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - backend

